List countrycodelist = [
  {"value": "AF - Afghanistan"},
  {"value": "AX - \u00c5land Islands"},
  {"value": "AL - Albania"},
  {"value": "DZ - Algeria"},
  {"value": "AS - American Samoa"},
  {"value": "AD - Andorra"},
  {"value": "AO - Angola"},
  {"value": "AI - Anguilla"},
  {"value": "AQ - Antarctica"},
  {"value": "AG - Antigua and Barbuda"},
  {"value": "AR - Argentina"},
  {"value": "AM - Armenia"},
  {"value": "AW - Aruba"},
  {"value": "AU - Australia"},
  {"value": "AT - Austria"},
  {"value": "AZ - Azerbaijan"},
  {"value": "BS - Bahamas"},
  {"value": "BH - Bahrain"},
  {"value": "BD - Bangladesh"},
  {"value": "BB - Barbados"},
  {"value": "BY - Belarus"},
  {"value": "BE - Belgium"},
  {"value": "BZ - Belize"},
  {"value": "BJ - Benin"},
  {"value": "BM - Bermuda"},
  {"value": "BT - Bhutan"},
  {"value": "BO - Bolivia, Plurinational State of"},
  {"value": "BQ - Bonaire, Sint Eustatius and Saba"},
  {"value": "BA - Bosnia and Herzegovina"},
  {"value": "BW - Botswana"},
  {"value": "BV - Bouvet Island"},
  {"value": "BR - Brazil"},
  {"value": "IO - British Indian Ocean Territory"},
  {"value": "BN - Brunei Darussalam"},
  {"value": "BG - Bulgaria"},
  {"value": "BF - Burkina Faso"},
  {"value": "BI - Burundi"},
  {"value": "KH - Cambodia"},
  {"value": "CM - Cameroon"},
  {"value": "CA - Canada"},
  {"value": "CV - Cape Verde"},
  {"value": "KY - Cayman Islands"},
  {"value": "CF - Central African Republic"},
  {"value": "TD - Chad"},
  {"value": "CL - Chile"},
  {"value": "CN - China"},
  {"value": "CX - Christmas Island"},
  {"value": "CC - Cocos (Keeling) Islands"},
  {"value": "CO - Colombia"},
  {"value": "KM - Comoros"},
  {"value": "CG - Congo"},
  {"value": "CD - Congo, the Democratic Republic of the"},
  {"value": "CK - Cook Islands"},
  {"value": "CR - Costa Rica"},
  {"value": "CI - C\u00f4te d'Ivoire"},
  {"value": "HR - Croatia"},
  {"value": "CU - Cuba"},
  {"value": "CW - Cura\u00e7ao"},
  {"value": "CY - Cyprus"},
  {"value": "CZ - Czech Republic"},
  {"value": "DK - Denmark"},
  {"value": "DJ - Djibouti"},
  {"value": "DM - Dominica"},
  {"value": "DO - Dominican Republic"},
  {"value": "EC - Ecuador"},
  {"value": "EG - Egypt"},
  {"value": "SV - El Salvador"},
  {"value": "GQ - Equatorial Guinea"},
  {"value": "ER - Eritrea"},
  {"value": "EE - Estonia"},
  {"value": "ET - Ethiopia"},
  {"value": "FK - Falkland Islands (Malvinas)"},
  {"value": "FO - Faroe Islands"},
  {"value": "FJ - Fiji"},
  {"value": "FI - Finland"},
  {"value": "FR - France"},
  {"value": "GF - French Guiana"},
  {"value": "PF - French Polynesia"},
  {"value": "TF - French Southern Territories"},
  {"value": "GA - Gabon"},
  {"value": "GM - Gambia"},
  {"value": "GE - Georgia"},
  {"value": "DE - Germany"},
  {"value": "GH - Ghana"},
  {"value": "GI - Gibraltar"},
  {"value": "GR - Greece"},
  {"value": "GL - Greenland"},
  {"value": "GD - Grenada"},
  {"value": "GP - Guadeloupe"},
  {"value": "GU - Guam"},
  {"value": "GT - Guatemala"},
  {"value": "GG - Guernsey"},
  {"value": "GN - Guinea"},
  {"value": "GW - Guinea Bissau"},
  {"value": "GY - Guyana"},
  {"value": "HT - Haiti"},
  {"value": "HM - Heard Island and McDonald Islands"},
  {"value": "VA - Holy See (Vatican City State)"},
  {"value": "HN - Honduras"},
  {"value": "HK - Hong Kong"},
  {"value": "HU - Hungary"},
  {"value": "IS - Iceland"},
  {"value": "IN - India"},
  {"value": "ID - Indonesia"},
  {"value": "IR - Iran, Islamic Republic of"},
  {"value": "IQ - Iraq"},
  {"value": "IE - Ireland"},
  {"value": "IM - Isle of Man"},
  {"value": "IL - Israel"},
  {"value": "IT - Italy"},
  {"value": "JM - Jamaica"},
  {"value": "JP - Japan"},
  {"value": "JE - Jersey"},
  {"value": "JO - Jordan"},
  {"value": "KZ - Kazakhstan"},
  {"value": "KE - Kenya"},
  {"value": "KI - Kiribati"},
  {"value": "KP - Korea, Democratic People's Republic of"},
  {"value": "KR - Korea, Republic of"},
  {"value": "KW - Kuwait"},
  {"value": "KG - Kyrgyzstan"},
  {"value": "LA - Lao People's Democratic Republic"},
  {"value": "LV - Latvia"},
  {"value": "LB - Lebanon"},
  {"value": "LS - Lesotho"},
  {"value": "LR - Liberia"},
  {"value": "LY - Libya"},
  {"value": "LI - Liechtenstein"},
  {"value": "LT - Lithuania"},
  {"value": "LU - Luxembourg"},
  {"value": "MO - Macao"},
  {"value": "MK - Macedonia, the Former Yugoslav Republic of"},
  {"value": "MG - Madagascar"},
  {"value": "MW - Malawi"},
  {"value": "MY - Malaysia"},
  {"value": "MV - Maldives"},
  {"value": "ML - Mali"},
  {"value": "MT - Malta"},
  {"value": "MH - Marshall Islands"},
  {"value": "MQ - Martinique"},
  {"value": "MR - Mauritania"},
  {"value": "MU - Mauritius"},
  {"value": "YT - Mayotte"},
  {"value": "MX - Mexico"},
  {"value": "FM - Micronesia, Federated States of"},
  {"value": "MD - Moldova, Republic of"},
  {"value": "MC - Monaco"},
  {"value": "MN - Mongolia"},
  {"value": "ME - Montenegro"},
  {"value": "MS - Montserrat"},
  {"value": "MA - Morocco"},
  {"value": "MZ - Mozambique"},
  {"value": "MM - Myanmar"},
  {"value": "NA - Namibia"},
  {"value": "NR - Nauru"},
  {"value": "NP - Nepal"},
  {"value": "NL - Netherlands"},
  {"value": "NC - New Caledonia"},
  {"value": "NZ - New Zealand"},
  {"value": "NI - Nicaragua"},
  {"value": "NE - Niger"},
  {"value": "NG - Nigeria"},
  {"value": "NU - Niue"},
  {"value": "NF - Norfolk Island"},
  {"value": "MP - Northern Mariana Islands"},
  {"value": "NO - Norway"},
  {"value": "OM - Oman"},
  {"value": "PK - Pakistan"},
  {"value": "PW - Palau"},
  {"value": "PS - Palestine, State of"},
  {"value": "PA - Panama"},
  {"value": "PG - Papua New Guinea"},
  {"value": "PY - Paraguay"},
  {"value": "PE - Peru"},
  {"value": "PH - Philippines"},
  {"value": "PN - Pitcairn"},
  {"value": "PL - Poland"},
  {"value": "PT - Portugal"},
  {"value": "PR - Puerto Rico"},
  {"value": "QA - Qatar"},
  {"value": "RE - R\u00e9union"},
  {"value": "RO - Romania"},
  {"value": "RU - Russian Federation"},
  {"value": "RW - Rwanda"},
  {"value": "BL - Saint Barth\u00e9lemy"},
  {"value": "SH - Saint Helena, Ascension and Tristan da Cunha"},
  {"value": "KN - Saint Kitts and Nevis"},
  {"value": "LC - Saint Lucia"},
  {"value": "MF - Saint Martin (French part)"},
  {"value": "PM - Saint Pierre and Miquelon"},
  {"value": "VC - Saint Vincent and the Grenadines"},
  {"value": "WS - Samoa"},
  {"value": "SM - San Marino"},
  {"value": "ST - Sao Tome and Principe"},
  {"value": "SA - Saudi Arabia"},
  {"value": "SN - Senegal"},
  {"value": "RS - Serbia"},
  {"value": "SC - Seychelles"},
  {"value": "SL - Sierra Leone"},
  {"value": "SG - Singapore"},
  {"value": "SX - Sint Maarten (Dutch part)"},
  {"value": "SK - Slovakia"},
  {"value": "SI - Slovenia"},
  {"value": "SB - Solomon Islands"},
  {"value": "SO - Somalia"},
  {"value": "ZA - South Africa"},
  {"value": "GS - South Georgia and the South Sandwich Islands"},
  {"value": "SS - South Sudan"},
  {"value": "ES - Spain"},
  {"value": "LK - Sri Lanka"},
  {"value": "SD - Sudan"},
  {"value": "SR - Suriname"},
  {"value": "SJ - Svalbard and Jan Mayen"},
  {"value": "SZ - Swaziland"},
  {"value": "SE - Sweden"},
  {"value": "CH - Switzerland"},
  {"value": "SY - Syrian Arab Republic"},
  {"value": "TW - Taiwan, Province of China"},
  {"value": "TJ - Tajikistan"},
  {"value": "TZ - Tanzania, United Republic of"},
  {"value": "TH - Thailand"},
  {"value": "TL - Timor Leste"},
  {"value": "TG - Togo"},
  {"value": "TK - Tokelau"},
  {"value": "TO - Tonga"},
  {"value": "TT - Trinidad and Tobago"},
  {"value": "TN - Tunisia"},
  {"value": "TR - Turkey"},
  {"value": "TM - Turkmenistan"},
  {"value": "TC - Turks and Caicos Islands"},
  {"value": "TV - Tuvalu"},
  {"value": "UG - Uganda"},
  {"value": "UA - Ukraine"},
  {"value": "AE - United Arab Emirates"},
  {"value": "GB - United Kingdom"},
  {"value": "US - United States"},
  {"value": "UM - United States Minor Outlying Islands"},
  {"value": "UY - Uruguay"},
  {"value": "UZ - Uzbekistan"},
  {"value": "VU - Vanuatu"},
  {"value": "VE - Venezuela, Bolivarian Republic of"},
  {"value": "VN - Viet Nam"},
  {"value": "VG - Virgin Islands, British"},
  {"value": "VI - Virgin Islands, U.S."},
  {"value": "WF - Wallis and Futuna"},
  {"value": "EH - Western Sahara"},
  {"value": "YE - Yemen"},
  {"value": "ZM - Zambia"},
  {"value": "ZW - Zimbabwe"},
];

List statecodelist = [
  {
    "value": "35 - Andaman and Nicobar Islands",
  },
  {
    "value": "37 - Andhra Pradesh",
  },
  {
    "value": "12 - Arunachal Pradesh",
  },
  {
    "value": "18 - Assam",
  },
  {
    "value": "10 - Bihar",
  },
  {
    "value": "04 - Chandigarh",
  },
  {
    "value": "22 - Chhattisgarh",
  },
  {
    "value": "26 - Dadra and Nagar Haveli",
  },
  {
    "value": "25 - Daman and Diu",
  },
  {
    "value": "07 - Delhi",
  },
  {
    "value": "30 - Goa",
  },
  {
    "value": "24 - Gujarat",
  },
  {
    "value": "06 - Haryana",
  },
  {
    "value": "02 - Himachal Pradesh",
  },
  {
    "value": "01 - Jammu and Kashmir",
  },
  {
    "value": "20 - Jharkhand",
  },
  {
    "value": "29 - Karnataka",
  },
  {
    "value": "32 - Kerala",
  },
  {
    "value": "31 - Lakshadweep Islands",
  },
  {
    "value": "23 - Madhya Pradesh",
  },
  {
    "value": "27 - Maharashtra",
  },
  {
    "value": "14 - Manipur",
  },
  {
    "value": "17 - Meghalaya",
  },
  {
    "value": "15 - Mizoram",
  },
  {
    "value": "13 - Nagaland",
  },
  {
    "value": "21 - Odisha",
  },
  {
    "value": "34 - Puducherry",
  },
  {
    "value": "03 - Punjab",
  },
  {
    "value": "08 - Rajasthan",
  },
  {
    "value": "11 - Sikkim",
  },
  {
    "value": "33 - Tamil Nadu",
  },
  {
    "value": "36 - Telangana",
  },
  {
    "value": "16 - Tripura",
  },
  {
    "value": "09 - Uttar Pradesh",
  },
  {
    "value": "05 - Uttarakhand",
  },
  {
    "value": "19 - West Bengal",
  },

  //  {
  //     "display": "UT-Ladakh",
  //     "value": "37",
  //   },
];

//  {"Code": "AF", "Name": "Afghanistan"},
//     {"Code": "AX", "Name": "\u00c5land Islands"},
//     {"Code": "AL", "Name": "Albania"},
//     {"Code": "DZ", "Name": "Algeria"},
//     {"Code": "AS", "Name": "American Samoa"},
//     {"Code": "AD", "Name": "Andorra"},
//     {"Code": "AO", "Name": "Angola"},
//     {"Code": "AI", "Name": "Anguilla"},
//     {"Code": "AQ", "Name": "Antarctica"},
//     {"Code": "AG", "Name": "Antigua and Barbuda"},
//     {"Code": "AR", "Name": "Argentina"},
//     {"Code": "AM", "Name": "Armenia"},
//     {"Code": "AW", "Name": "Aruba"},
//     {"Code": "AU", "Name": "Australia"},
//     {"Code": "AT", "Name": "Austria"},
//     {"Code": "AZ", "Name": "Azerbaijan"},
//     {"Code": "BS", "Name": "Bahamas"},
//     {"Code": "BH", "Name": "Bahrain"},
//     {"Code": "BD", "Name": "Bangladesh"},
//     {"Code": "BB", "Name": "Barbados"},
//     {"Code": "BY", "Name": "Belarus"},
//     {"Code": "BE", "Name": "Belgium"},
//     {"Code": "BZ", "Name": "Belize"},
//     {"Code": "BJ", "Name": "Benin"},
//     {"Code": "BM", "Name": "Bermuda"},
//     {"Code": "BT", "Name": "Bhutan"},
//     {"Code": "BO", "Name": "Bolivia, Plurinational State of"},
//     {"Code": "BQ", "Name": "Bonaire, Sint Eustatius and Saba"},
//     {"Code": "BA", "Name": "Bosnia and Herzegovina"},
//     {"Code": "BW", "Name": "Botswana"},
//     {"Code": "BV", "Name": "Bouvet Island"},
//     {"Code": "BR", "Name": "Brazil"},
//     {"Code": "IO", "Name": "British Indian Ocean Territory"},
//     {"Code": "BN", "Name": "Brunei Darussalam"},
//     {"Code": "BG", "Name": "Bulgaria"},
//     {"Code": "BF", "Name": "Burkina Faso"},
//     {"Code": "BI", "Name": "Burundi"},
//     {"Code": "KH", "Name": "Cambodia"},
//     {"Code": "CM", "Name": "Cameroon"},
//     {"Code": "CA", "Name": "Canada"},
//     {"Code": "CV", "Name": "Cape Verde"},
//     {"Code": "KY", "Name": "Cayman Islands"},
//     {"Code": "CF", "Name": "Central African Republic"},
//     {"Code": "TD", "Name": "Chad"},
//     {"Code": "CL", "Name": "Chile"},
//     {"Code": "CN", "Name": "China"},
//     {"Code": "CX", "Name": "Christmas Island"},
//     {"Code": "CC", "Name": "Cocos (Keeling) Islands"},
//     {"Code": "CO", "Name": "Colombia"},
//     {"Code": "KM", "Name": "Comoros"},
//     {"Code": "CG", "Name": "Congo"},
//     {"Code": "CD", "Name": "Congo, the Democratic Republic of the"},
//     {"Code": "CK", "Name": "Cook Islands"},
//     {"Code": "CR", "Name": "Costa Rica"},
//     {"Code": "CI", "Name": "C\u00f4te d'Ivoire"},
//     {"Code": "HR", "Name": "Croatia"},
//     {"Code": "CU", "Name": "Cuba"},
//     {"Code": "CW", "Name": "Cura\u00e7ao"},
//     {"Code": "CY", "Name": "Cyprus"},
//     {"Code": "CZ", "Name": "Czech Republic"},
//     {"Code": "DK", "Name": "Denmark"},
//     {"Code": "DJ", "Name": "Djibouti"},
//     {"Code": "DM", "Name": "Dominica"},
//     {"Code": "DO", "Name": "Dominican Republic"},
//     {"Code": "EC", "Name": "Ecuador"},
//     {"Code": "EG", "Name": "Egypt"},
//     {"Code": "SV", "Name": "El Salvador"},
//     {"Code": "GQ", "Name": "Equatorial Guinea"},
//     {"Code": "ER", "Name": "Eritrea"},
//     {"Code": "EE", "Name": "Estonia"},
//     {"Code": "ET", "Name": "Ethiopia"},
//     {"Code": "FK", "Name": "Falkland Islands (Malvinas)"},
//     {"Code": "FO", "Name": "Faroe Islands"},
//     {"Code": "FJ", "Name": "Fiji"},
//     {"Code": "FI", "Name": "Finland"},
//     {"Code": "FR", "Name": "France"},
//     {"Code": "GF", "Name": "French Guiana"},
//     {"Code": "PF", "Name": "French Polynesia"},
//     {"Code": "TF", "Name": "French Southern Territories"},
//     {"Code": "GA", "Name": "Gabon"},
//     {"Code": "GM", "Name": "Gambia"},
//     {"Code": "GE", "Name": "Georgia"},
//     {"Code": "DE", "Name": "Germany"},
//     {"Code": "GH", "Name": "Ghana"},
//     {"Code": "GI", "Name": "Gibraltar"},
//     {"Code": "GR", "Name": "Greece"},
//     {"Code": "GL", "Name": "Greenland"},
//     {"Code": "GD", "Name": "Grenada"},
//     {"Code": "GP", "Name": "Guadeloupe"},
//     {"Code": "GU", "Name": "Guam"},
//     {"Code": "GT", "Name": "Guatemala"},
//     {"Code": "GG", "Name": "Guernsey"},
//     {"Code": "GN", "Name": "Guinea"},
//     {"Code": "GW", "Name": "Guinea Bissau"},
//     {"Code": "GY", "Name": "Guyana"},
//     {"Code": "HT", "Name": "Haiti"},
//     {"Code": "HM", "Name": "Heard Island and McDonald Islands"},
//     {"Code": "VA", "Name": "Holy See (Vatican City State)"},
//     {"Code": "HN", "Name": "Honduras"},
//     {"Code": "HK", "Name": "Hong Kong"},
//     {"Code": "HU", "Name": "Hungary"},
//     {"Code": "IS", "Name": "Iceland"},
//     {"Code": "IN", "Name": "India"},
//     {"Code": "ID", "Name": "Indonesia"},
//     {"Code": "IR", "Name": "Iran, Islamic Republic of"},
//     {"Code": "IQ", "Name": "Iraq"},
//     {"Code": "IE", "Name": "Ireland"},
//     {"Code": "IM", "Name": "Isle of Man"},
//     {"Code": "IL", "Name": "Israel"},
//     {"Code": "IT", "Name": "Italy"},
//     {"Code": "JM", "Name": "Jamaica"},
//     {"Code": "JP", "Name": "Japan"},
//     {"Code": "JE", "Name": "Jersey"},
//     {"Code": "JO", "Name": "Jordan"},
//     {"Code": "KZ", "Name": "Kazakhstan"},
//     {"Code": "KE", "Name": "Kenya"},
//     {"Code": "KI", "Name": "Kiribati"},
//     {"Code": "KP", "Name": "Korea, Democratic People's Republic of"},
//     {"Code": "KR", "Name": "Korea, Republic of"},
//     {"Code": "KW", "Name": "Kuwait"},
//     {"Code": "KG", "Name": "Kyrgyzstan"},
//     {"Code": "LA", "Name": "Lao People's Democratic Republic"},
//     {"Code": "LV", "Name": "Latvia"},
//     {"Code": "LB", "Name": "Lebanon"},
//     {"Code": "LS", "Name": "Lesotho"},
//     {"Code": "LR", "Name": "Liberia"},
//     {"Code": "LY", "Name": "Libya"},
//     {"Code": "LI", "Name": "Liechtenstein"},
//     {"Code": "LT", "Name": "Lithuania"},
//     {"Code": "LU", "Name": "Luxembourg"},
//     {"Code": "MO", "Name": "Macao"},
//     {"Code": "MK", "Name": "Macedonia, the Former Yugoslav Republic of"},
//     {"Code": "MG", "Name": "Madagascar"},
//     {"Code": "MW", "Name": "Malawi"},
//     {"Code": "MY", "Name": "Malaysia"},
//     {"Code": "MV", "Name": "Maldives"},
//     {"Code": "ML", "Name": "Mali"},
//     {"Code": "MT", "Name": "Malta"},
//     {"Code": "MH", "Name": "Marshall Islands"},
//     {"Code": "MQ", "Name": "Martinique"},
//     {"Code": "MR", "Name": "Mauritania"},
//     {"Code": "MU", "Name": "Mauritius"},
//     {"Code": "YT", "Name": "Mayotte"},
//     {"Code": "MX", "Name": "Mexico"},
//     {"Code": "FM", "Name": "Micronesia, Federated States of"},
//     {"Code": "MD", "Name": "Moldova, Republic of"},
//     {"Code": "MC", "Name": "Monaco"},
//     {"Code": "MN", "Name": "Mongolia"},
//     {"Code": "ME", "Name": "Montenegro"},
//     {"Code": "MS", "Name": "Montserrat"},
//     {"Code": "MA", "Name": "Morocco"},
//     {"Code": "MZ", "Name": "Mozambique"},
//     {"Code": "MM", "Name": "Myanmar"},
//     {"Code": "NA", "Name": "Namibia"},
//     {"Code": "NR", "Name": "Nauru"},
//     {"Code": "NP", "Name": "Nepal"},
//     {"Code": "NL", "Name": "Netherlands"},
//     {"Code": "NC", "Name": "New Caledonia"},
//     {"Code": "NZ", "Name": "New Zealand"},
//     {"Code": "NI", "Name": "Nicaragua"},
//     {"Code": "NE", "Name": "Niger"},
//     {"Code": "NG", "Name": "Nigeria"},
//     {"Code": "NU", "Name": "Niue"},
//     {"Code": "NF", "Name": "Norfolk Island"},
//     {"Code": "MP", "Name": "Northern Mariana Islands"},
//     {"Code": "NO", "Name": "Norway"},
//     {"Code": "OM", "Name": "Oman"},
//     {"Code": "PK", "Name": "Pakistan"},
//     {"Code": "PW", "Name": "Palau"},
//     {"Code": "PS", "Name": "Palestine, State of"},
//     {"Code": "PA", "Name": "Panama"},
//     {"Code": "PG", "Name": "Papua New Guinea"},
//     {"Code": "PY", "Name": "Paraguay"},
//     {"Code": "PE", "Name": "Peru"},
//     {"Code": "PH", "Name": "Philippines"},
//     {"Code": "PN", "Name": "Pitcairn"},
//     {"Code": "PL", "Name": "Poland"},
//     {"Code": "PT", "Name": "Portugal"},
//     {"Code": "PR", "Name": "Puerto Rico"},
//     {"Code": "QA", "Name": "Qatar"},
//     {"Code": "RE", "Name": "R\u00e9union"},
//     {"Code": "RO", "Name": "Romania"},
//     {"Code": "RU", "Name": "Russian Federation"},
//     {"Code": "RW", "Name": "Rwanda"},
//     {"Code": "BL", "Name": "Saint Barth\u00e9lemy"},
//     {"Code": "SH", "Name": "Saint Helena, Ascension and Tristan da Cunha"},
//     {"Code": "KN", "Name": "Saint Kitts and Nevis"},
//     {"Code": "LC", "Name": "Saint Lucia"},
//     {"Code": "MF", "Name": "Saint Martin (French part)"},
//     {"Code": "PM", "Name": "Saint Pierre and Miquelon"},
//     {"Code": "VC", "Name": "Saint Vincent and the Grenadines"},
//     {"Code": "WS", "Name": "Samoa"},
//     {"Code": "SM", "Name": "San Marino"},
//     {"Code": "ST", "Name": "Sao Tome and Principe"},
//     {"Code": "SA", "Name": "Saudi Arabia"},
//     {"Code": "SN", "Name": "Senegal"},
//     {"Code": "RS", "Name": "Serbia"},
//     {"Code": "SC", "Name": "Seychelles"},
//     {"Code": "SL", "Name": "Sierra Leone"},
//     {"Code": "SG", "Name": "Singapore"},
//     {"Code": "SX", "Name": "Sint Maarten (Dutch part)"},
//     {"Code": "SK", "Name": "Slovakia"},
//     {"Code": "SI", "Name": "Slovenia"},
//     {"Code": "SB", "Name": "Solomon Islands"},
//     {"Code": "SO", "Name": "Somalia"},
//     {"Code": "ZA", "Name": "South Africa"},
//     {"Code": "GS", "Name": "South Georgia and the South Sandwich Islands"},
//     {"Code": "SS", "Name": "South Sudan"},
//     {"Code": "ES", "Name": "Spain"},
//     {"Code": "LK", "Name": "Sri Lanka"},
//     {"Code": "SD", "Name": "Sudan"},
//     {"Code": "SR", "Name": "Suriname"},
//     {"Code": "SJ", "Name": "Svalbard and Jan Mayen"},
//     {"Code": "SZ", "Name": "Swaziland"},
//     {"Code": "SE", "Name": "Sweden"},
//     {"Code": "CH", "Name": "Switzerland"},
//     {"Code": "SY", "Name": "Syrian Arab Republic"},
//     {"Code": "TW", "Name": "Taiwan, Province of China"},
//     {"Code": "TJ", "Name": "Tajikistan"},
//     {"Code": "TZ", "Name": "Tanzania, United Republic of"},
//     {"Code": "TH", "Name": "Thailand"},
//     {"Code": "TL", "Name": "Timor Leste"},
//     {"Code": "TG", "Name": "Togo"},
//     {"Code": "TK", "Name": "Tokelau"},
//     {"Code": "TO", "Name": "Tonga"},
//     {"Code": "TT", "Name": "Trinidad and Tobago"},
//     {"Code": "TN", "Name": "Tunisia"},
//     {"Code": "TR", "Name": "Turkey"},
//     {"Code": "TM", "Name": "Turkmenistan"},
//     {"Code": "TC", "Name": "Turks and Caicos Islands"},
//     {"Code": "TV", "Name": "Tuvalu"},
//     {"Code": "UG", "Name": "Uganda"},
//     {"Code": "UA", "Name": "Ukraine"},
//     {"Code": "AE", "Name": "United Arab Emirates"},
//     {"Code": "GB", "Name": "United Kingdom"},
//     {"Code": "US", "Name": "United States"},
//     {"Code": "UM", "Name": "United States Minor Outlying Islands"},
//     {"Code": "UY", "Name": "Uruguay"},
//     {"Code": "UZ", "Name": "Uzbekistan"},
//     {"Code": "VU", "Name": "Vanuatu"},
//     {"Code": "VE", "Name": "Venezuela, Bolivarian Republic of"},
//     {"Code": "VN", "Name": "Viet Nam"},
//     {"Code": "VG", "Name": "Virgin Islands, British"},
//     {"Code": "VI", "Name": "Virgin Islands, U.S."},
//     {"Code": "WF", "Name": "Wallis and Futuna"},
//     {"Code": "EH", "Name": "Western Sahara"},
//     {"Code": "YE", "Name": "Yemen"},
//     {"Code": "ZM", "Name": "Zambia"},
//     {"Code": "ZW", "Name": "Zimbabwe"},
