List countryData = [
  '+1---🇺🇸---US---United States',
  '+1---🇨🇦---CA---Canada',
  '+1242---🇧🇸---BS---Bahamas',
  '+1246---🇧🇧---BB---Barbados',
  '+1264---🇦🇮---AI---Anguilla',
  '+1268---🇦🇬---AG---Antigua and Barbuda',
  '+1284---🇻🇬---VG---Virgin Islands, British',
  '+1340---🇻🇮---VI---Virgin Islands, U.S.',
  '+1441---🇧🇲---BM---Bermuda',
  '+1473---🇬🇩---GD---Grenada',
  '+1649---🇹🇨---TC---Turks and Caicos Islands',
  '+1664---🇲🇸---MS---Montserrat',
  '+1670---🇲🇵---MP---Northern Mariana Islands',
  '+1671---🇬🇺---GU---Guam',
  '+1684---🇦🇸---AS---American Samoa',
  '+1758---🇱🇨---LC---Saint Lucia',
  '+1767---🇩🇲---DM---Dominica',
  '+1784---🇻🇨---VC---Saint Vincent and the Grenadines',
  '+1849---🇩🇴---DO---Dominican Republic',
  '+1868---🇹🇹---TT---Trinidad and Tobago',
  '+1869---🇰🇳---KN---Saint Kitts and Nevis',
  '+1876---🇯🇲---JM---Jamaica',
  '+1939---🇵🇷---PR---Puerto Rico',
  '+20---🇪🇬---EG---Egypt',
  '+211---🇸🇸---SS---South Sudan',
  '+212---🇲🇦---MA---Morocco',
  '+213---🇩🇿---DZ---Algeria',
  '+216---🇹🇳---TN---Tunisia',
  '+218---🇱🇾---LY---Libyan Arab Jamahiriya',
  '+220---🇬🇲---GM---Gambia',
  '+221---🇸🇳---SN---Senegal',
  '+222---🇲🇷---MR---Mauritania',
  '+223---🇲🇱---ML---Mali',
  '+224---🇬🇳---GN---Guinea',
  '+225---🇨🇮---CI---Cote d\'Ivoire',
  '+226---🇧🇫---BF---Burkina Faso',
  '+227---🇳🇪---NE---Niger',
  '+228---🇹🇬---TG---Togo',
  '+229---🇧🇯---BJ---Benin',
  '+230---🇲🇺---MU---Mauritius',
  '+231---🇱🇷---LR---Liberia',
  '+232---🇸🇱---SL---Sierra Leone',
  '+233---🇬🇭---GH---Ghana',
  '+234---🇳🇬---NG---Nigeria',
  '+235---🇹🇩---TD---Chad',
  '+236---🇨🇫---CF---Central African Republic',
  '+237---🇨🇲---CM---Cameroon',
  '+238---🇨🇻---CV---Cape Verde',
  '+239---🇸🇹---ST---Sao Tome and Principe',
  '+240---🇬🇶---GQ---Equatorial Guinea',
  '+241---🇬🇦---GA---Gabon',
  '+242---🇨🇬---CG---Congo',
  '+243---🇨🇩---CD---Congo, The Democratic Republic of the Congo',
  '+244---🇦🇴---AO---Angola',
  '+245---🇬🇼---GW---Guinea-Bissau',
  '+246---🇮🇴---IO---British Indian Ocean Territory',
  '+248---🇸🇨---SC---Seychelles',
  '+249---🇸🇩---SD---Sudan',
  '+250---🇷🇼---RW---Rwanda',
  '+251---🇪🇹---ET---Ethiopia',
  '+252---🇸🇴---SO---Somalia',
  '+253---🇩🇯---DJ---Djibouti',
  '+254---🇰🇪---KE---Kenya',
  '+255---🇹🇿---TZ---Tanzania, United Republic of Tanzania',
  '+256---🇺🇬---UG---Uganda',
  '+257---🇧🇮---BI---Burundi',
  '+258---🇲🇿---MZ---Mozambique',
  '+260---🇿🇲---ZM---Zambia',
  '+261---🇲🇬---MG---Madagascar',
  '+262---🇹🇫---TF---French Southern Territories',
  '+262---🇾🇹---YT---Mayotte',
  '+263---🇿🇼---ZW---Zimbabwe',
  '+264---🇳🇦---NA---Namibia',
  '+265---🇲🇼---MW---Malawi',
  '+266---🇱🇸---LS---Lesotho',
  '+267---🇧🇼---BW---Botswana',
  '+268---🇸🇿---SZ---Swaziland',
  '+269---🇰🇲---KM---Comoros',
  '+27---🇿🇦---ZA---South Africa',
  '+290---🇸🇭---SH---Saint Helena, Ascension and Tristan Da Cunha',
  '+291---🇪🇷---ER---Eritrea',
  '+297---🇦🇼---AW---Aruba',
  '+298---🇫🇴---FO---Faroe Islands',
  '+299---🇬🇱---GL---Greenland',
  '+30---🇬🇷---GR---Greece',
  '+31---🇳🇱---NL---Netherlands',
  '+32---🇧🇪---BE---Belgium',
  '+33---🇫🇷---FR---France',
  '+34---🇪🇸---ES---Spain',
  '+345---🇰🇾---KY---Cayman Islands',
  '+350---🇬🇮---GI---Gibraltar',
  '+351---🇵🇹---PT---Portugal',
  '+352---🇱🇺---LU---Luxembourg',
  '+353---🇮🇪---IE---Ireland',
  '+354---🇮🇸---IS---Iceland',
  '+355---🇦🇱---AL---Albania',
  '+356---🇲🇹---MT---Malta',
  '+357---🇨🇾---CY---Cyprus',
  '+358---🇦🇽---AX---Åland Islands',
  '+358---🇫🇮---FI---Finland',
  '+359---🇧🇬---BG---Bulgaria',
  '+36---🇭🇺---HU---Hungary',
  '+370---🇱🇹---LT---Lithuania',
  '+371---🇱🇻---LV---Latvia',
  '+372---🇪🇪---EE---Estonia',
  '+373---🇲🇩---MD---Moldova',
  '+374---🇦🇲---AM---Armenia',
  '+375---🇧🇾---BY---Belarus',
  '+376---🇦🇩---AD---Andorra',
  '+377---🇲🇨---MC---Monaco',
  '+378---🇸🇲---SM---San Marino',
  '+379---🇻🇦---VA---Holy See (Vatican City State)',
  '+380---🇺🇦---UA---Ukraine',
  '+381---🇷🇸---RS---Serbia',
  '+382---🇲🇪---ME---Montenegro',
  '+383---🇽🇰---XK---Kosovo',
  '+385---🇭🇷---HR---Croatia',
  '+386---🇸🇮---SI---Slovenia',
  '+387---🇧🇦---BA---Bosnia and Herzegovina',
  '+389---🇲🇰---MK---Macedonia',
  '+39---🇮🇹---IT---Italy',
  '+40---🇷🇴---RO---Romania',
  '+41---🇨🇭---CH---Switzerland',
  '+420---🇨🇿---CZ---Czech Republic',
  '+421---🇸🇰---SK---Slovakia',
  '+423---🇱🇮---LI---Liechtenstein',
  '+43---🇦🇹---AT---Austria',
  '+44---🇬🇬---GG---Guernsey',
  '+44---🇮🇲---IM---Isle of Man',
  '+44---🇯🇪---JE---Jersey',
  '+44---🇬🇧---GB---United Kingdom',
  '+45---🇩🇰---DK---Denmark',
  '+46---🇸🇪---SE---Sweden',
  '+47---🇧🇻---BV---Bouvet Island',
  '+47---🇳🇴---NO---Norway',
  '+47---🇸🇯---SJ---Svalbard and Jan Mayen',
  '+48---🇵🇱---PL---Poland',
  '+49---🇩🇪---DE---Germany',
  '+500---🇫🇰---FK---Falkland Islands (Malvinas)',
  '+500---🇬🇸---GS---South Georgia and the South Sandwich Islands',
  '+501---🇧🇿---BZ---Belize',
  '+502---🇬🇹---GT---Guatemala',
  '+503---🇸🇻---SV---El Salvador',
  '+504---🇭🇳---HN---Honduras',
  '+505---🇳🇮---NI---Nicaragua',
  '+506---🇨🇷---CR---Costa Rica',
  '+507---🇵🇦---PA---Panama',
  '+508---🇵🇲---PM---Saint Pierre and Miquelon',
  '+509---🇭🇹---HT---Haiti',
  '+51---🇵🇪---PE---Peru',
  '+52---🇲🇽---MX---Mexico',
  '+53---🇨🇺---CU---Cuba',
  '+54---🇦🇷---AR---Argentina',
  '+55---🇧🇷---BR---Brazil',
  '+5511---🇧🇷---BR---Brazil (São Paulo)',
  '+5512---🇧🇷---BR---Brazil (São Paulo)',
  '+5513---🇧🇷---BR---Brazil (São Paulo)',
  '+5514---🇧🇷---BR---Brazil (São Paulo)',
  '+5515---🇧🇷---BR---Brazil (São Paulo)',
  '+5516---🇧🇷---BR---Brazil (São Paulo)',
  '+5517---🇧🇷---BR---Brazil (São Paulo)',
  '+5518---🇧🇷---BR---Brazil (São Paulo)',
  '+5519---🇧🇷---BR---Brazil (São Paulo)',
  '+5521---🇧🇷---BR---Brazil (Rio de Janeiro)',
  '+5522---🇧🇷---BR---Brazil (Rio de Janeiro)',
  '+5524---🇧🇷---BR---Brazil (Rio de Janeiro)',
  '+5527---🇧🇷---BR---Brazil (Espírito Santo)',
  '+5528---🇧🇷---BR---Brazil (Espírito Santo)',
  '+5531---🇧🇷---BR---Brazil (Minas Gerais)',
  '+5532---🇧🇷---BR---Brazil (Minas Gerais)',
  '+5533---🇧🇷---BR---Brazil (Minas Gerais)',
  '+5534---🇧🇷---BR---Brazil (Minas Gerais)',
  '+5535---🇧🇷---BR---Brazil (Minas Gerais)',
  '+5537---🇧🇷---BR---Brazil (Minas Gerais)',
  '+5538---🇧🇷---BR---Brazil (Minas Gerais)',
  '+5541---🇧🇷---BR---Brazil (Paraná)',
  '+5542---🇧🇷---BR---Brazil (Paraná)',
  '+5543---🇧🇷---BR---Brazil (Paraná)',
  '+5544---🇧🇷---BR---Brazil (Paraná)',
  '+5545---🇧🇷---BR---Brazil (Paraná)',
  '+5546---🇧🇷---BR---Brazil (Paraná)',
  '+5547---🇧🇷---BR---Brazil (Santa Catarina)',
  '+5548---🇧🇷---BR---Brazil (Santa Catarina)',
  '+5549---🇧🇷---BR---Brazil (Santa Catarina)',
  '+5551---🇧🇷---BR---Brazil (Rio Grande do Sul)',
  '+5553---🇧🇷---BR---Brazil (Rio Grande do Sul)',
  '+5554---🇧🇷---BR---Brazil (Rio Grande do Sul)',
  '+5555---🇧🇷---BR---Brazil (Rio Grande do Sul)',
  '+5561---🇧🇷---BR---Brazil (Distrito Federal)',
  '+5562---🇧🇷---BR---Brazil (Goiás)',
  '+5563---🇧🇷---BR---Brazil (Tocantins)',
  '+5564---🇧🇷---BR---Brazil (Goiás)',
  '+5565---🇧🇷---BR---Brazil (Mato Grosso)',
  '+5566---🇧🇷---BR---Brazil (Mato Grosso)',
  '+5567---🇧🇷---BR---Brazil (Mato Grosso do Sul)',
  '+5568---🇧🇷---BR---Brazil (Acre)',
  '+5569---🇧🇷---BR---Brazil (Rondônia)',
  '+5571---🇧🇷---BR---Brazil (Bahia)',
  '+5573---🇧🇷---BR---Brazil (Bahia)',
  '+5574---🇧🇷---BR---Brazil (Bahia)',
  '+5575---🇧🇷---BR---Brazil (Bahia)',
  '+5577---🇧🇷---BR---Brazil (Bahia)',
  '+5579---🇧🇷---BR---Brazil (Sergipe)',
  '+5581---🇧🇷---BR---Brazil (Pernambuco)',
  '+5582---🇧🇷---BR---Brazil (Alagoas)',
  '+5583---🇧🇷---BR---Brazil (Paraíba)',
  '+5584---🇧🇷---BR---Brazil (Rio Grande do Norte)',
  '+5585---🇧🇷---BR---Brazil (Ceará)',
  '+5586---🇧🇷---BR---Brazil (Piauí)',
  '+5587---🇧🇷---BR---Brazil (Pernambuco)',
  '+5588---🇧🇷---BR---Brazil (Ceará)',
  '+5589---🇧🇷---BR---Brazil (Piauí)',
  '+5591---🇧🇷---BR---Brazil (Piauí)',
  '+5592---🇧🇷---BR---Brazil (Amazonas)',
  '+5593---🇧🇷---BR---Brazil (Pará)',
  '+5594---🇧🇷---BR---Brazil (Pará)',
  '+5595---🇧🇷---BR---Brazil (Roraima)',
  '+5596---🇧🇷---BR---Brazil (Amapá)',
  '+5597---🇧🇷---BR---Brazil (Amazonas)',
  '+5598---🇧🇷---BR---Brazil (Maranhão)',
  '+5599---🇧🇷---BR---Brazil (Maranhão)',
  '+56---🇨🇱---CL---Chile',
  '+57---🇨🇴---CO---Colombia',
  '+58---🇻🇪---VE---Venezuela, Bolivarian Republic of Venezuela',
  '+590---🇬🇵---GP---Guadeloupe',
  '+590---🇧🇱---BL---Saint Barthelemy',
  '+590---🇲🇫---MF---Saint Martin',
  '+591---🇧🇴---BO---Bolivia, Plurinational State of bolivia',
  '+592---🇬🇾---GY---Guyana',
  '+593---🇪🇨---EC---Ecuador',
  '+594---🇬🇫---GF---French Guiana',
  '+595---🇵🇾---PY---Paraguay',
  '+596---🇲🇶---MQ---Martinique',
  '+597---🇸🇷---SR---Suriname',
  '+598---🇺🇾---UY---Uruguay',
  '+599------AN---Netherlands Antilles',
  '+60---🇲🇾---MY---Malaysia',
  '+61---🇦🇺---AU---Australia',
  '+61---🇨🇽---CX---Christmas Island',
  '+61---🇨🇨---CC---Cocos (Keeling) Islands',
  '+62---🇮🇩---ID---Indonesia',
  '+63---🇵🇭---PH---Philippines',
  '+64---🇳🇿---NZ---New Zealand',
  '+64---🇵🇳---PN---Pitcairn',
  '+65---🇸🇬---SG---Singapore',
  '+66---🇹🇭---TH---Thailand',
  '+670---🇹🇱---TL---Timor-Leste',
  '+672---🇦🇶---AQ---Antarctica',
  '+672---🇭🇲---HM---Heard Island and Mcdonald Islands',
  '+672---🇳🇫---NF---Norfolk Island',
  '+673---🇧🇳---BN---Brunei Darussalam',
  '+674---🇳🇷---NR---Nauru',
  '+675---🇵🇬---PG---Papua New Guinea',
  '+676---🇹🇴---TO---Tonga',
  '+677---🇸🇧---SB---Solomon Islands',
  '+678---🇻🇺---VU---Vanuatu',
  '+679---🇫🇯---FJ---Fiji',
  '+680---🇵🇼---PW---Palau',
  '+681---🇼🇫---WF---Wallis and Futuna',
  '+682---🇨🇰---CK---Cook Islands',
  '+683---🇳🇺---NU---Niue',
  '+685---🇼🇸---WS---Samoa',
  '+686---🇰🇮---KI---Kiribati',
  '+687---🇳🇨---NC---New Caledonia',
  '+688---🇹🇻---TV---Tuvalu',
  '+689---🇵🇫---PF---French Polynesia',
  '+690---🇹🇰---TK---Tokelau',
  '+691---🇫🇲---FM---Micronesia, Federated States of Micronesia',
  '+692---🇲🇭---MH---Marshall Islands',
  '+7---🇷🇺---RU---Russia',
  '+7---🇰🇿---KZ---Kazakhstan',
  '+81---🇯🇵---JP---Japan',
  '+82---🇰🇷---KR---Korea, Republic of South Korea',
  '+84---🇻🇳---VN---Vietnam',
  '+850---🇰🇵---KP---Korea, Democratic People\'s Republic of Korea',
  '+852---🇭🇰---HK---Hong Kong',
  '+853---🇲🇴---MO---Macao',
  '+855---🇰🇭---KH---Cambodia',
  '+856---🇱🇦---LA---Laos',
  '+86---🇨🇳---CN---China',
  '+880---🇧🇩---BD---Bangladesh',
  '+886---🇹🇼---TW---Taiwan',
  '+90---🇹🇷---TR---Turkey',
  '+91---🇮🇳---IN---India',
  '+92---🇵🇰---PK---Pakistan',
  '+93---🇦🇫---AF---Afghanistan',
  '+94---🇱🇰---LK---Sri Lanka',
  '+95---🇲🇲---MM---Myanmar',
  '+960---🇲🇻---MV---Maldives',
  '+961---🇱🇧---LB---Lebanon',
  '+962---🇯🇴---JO---Jordan',
  '+963---🇸🇾---SY---Syrian Arab Republic',
  '+964---🇮🇶---IQ---Iraq',
  '+965---🇰🇼---KW---Kuwait',
  '+966---🇸🇦---SA---Saudi Arabia',
  '+967---🇾🇪---YE---Yemen',
  '+968---🇴🇲---OM---Oman',
  '+970---🇵🇸---PS---Palestinian Territory, Occupied',
  '+971---🇦🇪---AE---United Arab Emirates',
  '+972---🇮🇱---IL---Israel',
  '+973---🇧🇭---BH---Bahrain',
  '+974---🇶🇦---QA---Qatar',
  '+975---🇧🇹---BT---Bhutan',
  '+976---🇲🇳---MN---Mongolia',
  '+977---🇳🇵---NP---Nepal',
  '+98---🇮🇷---IR---Iran, Islamic Republic of Persian Gulf',
  '+992---🇹🇯---TJ---Tajikistan',
  '+993---🇹🇲---TM---Turkmenistan',
  '+994---🇦🇿---AZ---Azerbaijan',
  '+995---🇬🇪---GE---Georgia',
  '+996---🇰🇬---KG---Kyrgyzstan',
  '+998---🇺🇿---UZ---Uzbekistan',
];
